project:
  type: website

website:
  title: "Data Science Project Setup"
  page-navigation: true

  sidebar:
    title: "Data Science Project Setup"
    logo: "assets/logo.png"
    align: center
    logo-alt: "University of Bristol"
    style: "docked"
    border: true
    contents:
      - href: "index.qmd"
        text: "Home"

      - href: "pages/01-python.qmd"
        text: "Python"

      - href: "pages/02-R.qmd"
        text: "R"

      - href: "pages/03-terminal-cheatsheet.qmd"
        text: "Terminal Cheatsheet"

      - href: "pages/04-FAQs.qmd"
        text: "FAQs"


  page-footer:
    left: "Course delivered by the [Jean Golding Institute](https://www.bristol.ac.uk/golding/)<br>© [CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/)"

  repo-url: https://github.com/bristol-training/data-science-project-setup
  repo-actions: [edit, issue]

format:
  html:
    theme: [cosmo, style.scss]
    toc: true

execute:
  freeze: auto